apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  namespace: demo
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::027330342406:role/S3BucketAccessK8SRole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prahar
  namespace: demo
spec:
  selector:
    matchLabels:
      app: demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      serviceAccountName: app
      initContainers:
      - name: initialize-container
        image: amazon/aws-cli
        command: ["/bin/bash","-c"]
        args: ["aws s3 cp s3://prahar/index.html /demo/"]
        volumeMounts:
        - name: myvol
          mountPath: /demo
      containers:
      - name: demo-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: myvol
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: myvol
        emptyDir: {}
